## NUMPY

In [2]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
[[1, 2, 3, 4], 
 [5, 6, 7, 8], 
 [9, 10, 11, 12]
]

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ])
print(a)
print(a.ndim)
print(a.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [14]:
a[1][2]

7

In [15]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [21]:
np.zeros((2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [23]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [25]:
np.empty((2, 2))

array([[1., 1.],
       [1., 1.]])

In [26]:
list(range(5))

[0, 1, 2, 3, 4]

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
a_list = list(range(10))
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
a_list.append(list(range(3)))

In [32]:
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2]]

In [35]:
a_numpy = np.arange(10)
a_numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
np.append(a_numpy, range(3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [44]:
np.append(a_numpy, np.arange(6).reshape(3, 2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5])

In [47]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [7, 8, 9]], axis=1)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 7, 8, 9]])

In [48]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.array([7, 8, 9])

array([7, 8, 9])

In [54]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9, 10]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2], 0, 1, 2]

In [56]:
for i in range(3):
    a_list.append(i)
print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2], 0, 1, 2]


In [67]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

axis=0 baris

axis=1 kolom

In [63]:
np.delete(a, -1, axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
np.sort(a)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
12


In [72]:
a.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [89]:
a[:, np.newaxis]

(5, 1)

In [90]:
a

array([0, 1, 2, 3, 4])

In [93]:
np.expand_dims(a, axis=1).shape

(5, 1)

## Indexing Slicing

In [94]:
a = np.array([0, 1, 2, 3, 4, 5])

In [97]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [98]:
a[0:3]

array([0, 1, 2])

In [99]:
a[:3]

array([0, 1, 2])

In [100]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [101]:
a[-3:]

array([3, 4, 5])

In [102]:
a[:-1]

array([0, 1, 2, 3, 4])

In [104]:
a > 2

array([False, False, False,  True,  True,  True])

In [105]:
a[np.array([False, False, False,  True,  True,  True])]

array([3, 4, 5])

In [106]:
a[a>2]

array([3, 4, 5])

In [109]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

In [117]:
above_five = a > 8

In [119]:
a[above_five]

array([ 9, 10, 11])

In [ ]:
# True False

In [ ]:
# ==
# >=
# <=
# >
# <

In [121]:
a * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [122]:
a_list * 2

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 [0, 1, 2],
 0,
 1,
 2,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 [0, 1, 2],
 0,
 1,
 2]

In [125]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [126]:
genap = a % 2 == 0

a[genap]

array([ 0,  2,  4,  6,  8, 10])

In [127]:
a[(a > 2) & (a < 11) & (a % 2 != 0)]

array([3, 5, 7, 9])

In [131]:
a_1 = np.array(([1, 2], [2, 2]))
a_2 = np.array(([3, 3], [4, 4]))

In [133]:
np.vstack([a_1, a_2])

array([[1, 2],
       [2, 2],
       [3, 3],
       [4, 4]])

In [134]:
np.hstack([a_1, a_2])

array([[1, 2, 3, 3],
       [2, 2, 4, 4]])

In [143]:
arrsplit = np.arange(1, 25).reshape(2, 12)
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [144]:
h_1, h_2, h_3 = np.hsplit(arrsplit, 3)

In [145]:
h_1

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [141]:
h_2

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [142]:
h_3

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [139]:
np.vsplit(arrsplit, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [150]:
b = a

In [151]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
np.delete(b, -1, 0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# dataframe
# backup_dataframe = dataframe.copy()

In [ ]:
# dataframe = backup_dataframe.copy()

In [155]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [156]:
a * np.ones(12).reshape(3, 4) * 3

array([[ 0.,  3.,  6.,  9.],
       [12., 15., 18., 21.],
       [24., 27., 30., 33.]])

In [ ]:
# a b     x      a b
# c d            c d

In [ ]:
np.dot

In [157]:
np.arange(5).sum() # method call

10

In [160]:
np.sum(a) # function call

66

In [ ]:
np.sum()
np.absolute()
np.mean()
np.median()
np.add()
np.subtract()
np.nansum()

In [161]:
np.array([np.nan, 5]).sum()

nan

In [163]:
np.nansum(np.array([np.nan, 5]))

5.0

In [164]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [165]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.linspace(1, 4, num=4)

In [170]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [171]:
b.sum(axis=1)

array([2, 4])

In [172]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [174]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [178]:
x1 = np.linspace(5, 122, num=4).reshape(2, 2)
x2 = np.linspace(8, 32, num=4).reshape(2, 2)

In [180]:
x1

array([[  5.,  44.],
       [ 83., 122.]])

In [181]:
x2

array([[ 8., 16.],
       [24., 32.]])

In [182]:
x1 * x2

array([[  40.,  704.],
       [1992., 3904.]])

In [184]:
np.product([x1, x2], axis=0)

array([[  40.,  704.],
       [1992., 3904.]])

In [186]:
np.maximum(x1, x2)

array([[  8.,  44.],
       [ 83., 122.]])

In [187]:
np.minimum(x1, x2)

array([[ 5., 16.],
       [24., 32.]])

In [189]:
np.std([x1, x2], axis=0)

array([[ 1.5, 14. ],
       [29.5, 45. ]])

In [190]:
np.min(x2)

8.0

In [191]:
np.median(x1)

63.5

In [195]:
np.random.randint(1, 100, size=10)

array([91, 20, 88, 75, 19, 60, 47, 32,  3, 63])

In [196]:
np.random.randn(3, 4)

array([[ 1.53580639,  0.06232179,  0.10306937,  1.40450854],
       [ 0.56761344, -1.00629558,  0.39998896, -0.6396051 ],
       [ 1.26932249,  0.56498708, -0.52716521,  0.79592916]])

In [201]:
d = np.random.randn(4, 3)

In [202]:
a * d

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [205]:
a.dot(d)

array([[  7.29810533,  -0.81542882,   0.19996511],
       [ 15.87807196,   3.8955684 ,  -8.4264068 ],
       [ 24.4580386 ,   8.60656563, -17.05277871]])

In [206]:
np.dot(a, d)

array([[  7.29810533,  -0.81542882,   0.19996511],
       [ 15.87807196,   3.8955684 ,  -8.4264068 ],
       [ 24.4580386 ,   8.60656563, -17.05277871]])

In [209]:
d[1:3, 1]

array([ 2.27797105, -0.2504618 ])

In [ ]:
# d[baris, kolom]

In [210]:
d.transpose()

array([[-1.86745465,  2.30633812,  0.12655735,  1.57955084],
       [ 0.01439881,  2.27797105, -0.2504618 , -0.86415876],
       [-1.67481298, -0.77750516, -0.09029481,  0.38601996]])

In [212]:
np.transpose(d)

array([[-1.86745465,  2.30633812,  0.12655735,  1.57955084],
       [ 0.01439881,  2.27797105, -0.2504618 , -0.86415876],
       [-1.67481298, -0.77750516, -0.09029481,  0.38601996]])